### ISSUE TITLE
请教：ford avdata IMU

### ISSUE THREAD

**Issue by huanhexiao** [Saixiaoma/SLAM-Studying#1]
你好兄弟，能否请教下ford av的IMU数据该怎么处理？

**Comment by Saixiaoma** [comment]
这个是我一个师兄之前弄的，现在毕业了，我没弄这个啦。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;huanhexiao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月24日(星期二) 下午5:16
收件人:&nbsp;&quot;Saixiaoma/SLAM-Studying&quot;<SLAM-Studying@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Saixiaoma/SLAM-Studying] 请教：ford avdata IMU (#1)

**Comment by huanhexiao** [comment]
好吧
